name: PHP tests

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            php-versions: ['8.0', '8.1', '8.2', '8.3', 'latest']
          fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
    - name: Prepare
      run: |
        composer install --optimize-autoloader
        chmod +x ./bin/*.sh
    - name: Run tests
      run: ./bin/tests.sh
    - name: Run static analysis
      continue-on-error: true
      run: ./bin/phpstan.sh
