name: PHP tests

on:
  push:
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            php-versions: ['8.0', '8.1', '8.2', '8.3', 'latest']
            c4p-tests-task-message-protocol-version: ['1', '2']
            c4p-tests-broker-driver:
              - PredisRedisDriver
              - PhpAmqpLibAmqpDriver
            c4p-tests-backend-driver:
              - PredisRedisDriver
          fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
    - name: "Prepare: Install PHP dependencies + prepare scripts"
      run: |
        composer install --optimize-autoloader
        chmod +x ./bin/*.sh
    - name: "Infra: Setup services"
      run: ./bin/tests.sh -s infra:setup
    - name: Run tests
      run: ./bin/tests.sh -s tests
      env:
        C4P_TESTS_TASK_MESSAGE_PROTOCOL_VERSION: ${{ matrix.c4p-tests-task-message-protocol-version }}
        C4P_TESTS_BROKER_DRIVER: ${{ matrix.c4p-tests-broker-driver }}
        C4P_TESTS_BACKEND_DRIVER: ${{ matrix.c4p-tests-backend-driver }}
    - name: "Infra: Tear down services"
      run: ./bin/tests.sh -s infra:teardown
    - name: Run code style analysis
      continue-on-error: false
      run: ./bin/code-style.sh
    - name: Run static analysis
      continue-on-error: true
      run: ./bin/phpstan.sh
